@@grammar::Calc


start
    =
    expression $
    ;

#include :: "pin/src/resources/type.ebnf"

# 표현식
expression
    =
    | addition
    | subtraction
    | term
    ;

# 덧셈
addition
    =
    left:expression op:'+' ~ right:term
    ;

# 뺄셈
subtraction
    =
    left:expression op:'-' ~ right:term
    ;

# 항
term
    =
    | multiplication
    | division
    | factor
    ;

# 거듭제곱
multiplication
    =
    left:term op:'**' ~ right:factor
    ;

# 곱셈
multiplication
    =
    left:term op:'*' ~ right:factor
    ;

# 나눗셈
division
    =
    left:term '/' ~ right:factor
    ;

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | number
    ;

