@@grammar::Declaration
@@whitespace :: /[ \t\r\f\v]+/


start
    =
        identifier:   identifier
        specifier:    ':'
        [type_specifier: type_specifier]

        $;

assignation = ':' '=';

#include :: "pin/src/resources/type.ebnf"

# x : int = 3
# x := 3
# x :: 3
# x : int : 3

expression_terminator = "\n";
identifier = /[a-zA-Zㄱ-ㅣ가-힣_][a-zA-Zㄱ-ㅣ가-힣0-9_]*/;