@@grammar::Pin
@@whitespace :: /[ \t\r\f\v]+/


start
    =
       {stmt}
    ;

type
    =
    | 'int' | 'i8' | 'i16' | 'i32' | 'i64'
    | 'uint'| 'u8' | 'u16' | 'u32' | 'u64'
    ;

stmt
    =
    | terminator
    | varStmt
    | constStmt
    ;

constStmt = ','.{ const }+ terminator ;
const = ident:const_id ":" [type:type] ":" expr:expr ;

varStmt = ','.{ var }+ terminator ;
var = varAsgn | varDecl ;
varDecl = ident:id ":" type:type ;
varAsgn = ident:id ":" [type:type] "=" expr:expr ;

# TODO: fix
expr = id | integer;

integer::int
    =
    /\d+/
    ;

float::float
    =
    /\d+\.\d+/
    ;


terminator = '\n' | ';' ;

const_id = /[A-Zㄱ-ㅣ가-힣_][A-Zㄱ-ㅣ가-힣0-9_]*/;
id = /[a-zA-Zㄱ-ㅣ가-힣_][a-zA-Zㄱ-ㅣ가-힣0-9_]*/;