@@grammar::CALC

start
    =
    expression $
    ;

# 표현식
expression
    =
    | addition
    | subtraction
    | term
    ;
addition
    =
    left:expression op:'+' ~ right:term
    ;

subtraction
    =
    left:expression op:'-' ~ right:term
    ;

# 항
term
    =
    | multiplication
    | division
    | factor
    ;


multiplication
    =
    left:term op:'*' ~ right:factor
    ;


division
    =
    left:term '/' ~ right:factor
    ;

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | number
    ;

number
    =
    /\d+/
    ;

newlines = {'\n'};
terminate = '\n' | ';' ;