@@grammar::CALC

start
    =
    expression $
    ;

# 표현식
expression
    =
    | left:expression op:'+' ~ right:term
    | left:expression op:'-' ~ right:term
    | term
    ;

# 항
term
    =
    | left:term op:'*' ~ right:factor
    | left:term op:'/' ~ right:factor
    | factor
    ;

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | number
    ;

number
    =
    /\d+/
    ;

newlines = {'\n'};
terminate = '\n' | ';' ;