assignment_operator
    =
    | '='
    | '*='
    | '/='
    | '%='
    | '+='
    | '-='
    | '<<='
    | '>>='
    | '&='
    | '^='
    | '|='
    ;

unary_operator =
    | '&'
    | '*'
    | '+'
    | '-'
    | '~'
    | '!'
    ;