type_specifier
    =
    | int_type
    | float_type
    | bool_type
    | string_type
    | unit_type
    ;


int_type
    =
    | 'int' | 'i8' | 'i16' | 'i32' | 'i64'
    | 'uint'| 'u8' | 'u16' | 'u32' | 'u64'
    ;

float_type
    =
    | 'f32'
    | 'f64'
    ;

bool_type
    =
    | 'bool'
    ;

unit_type
    =
    | 'Unit'
    ;


string_type
    =
    | 'String'
    ;

# 숫자 정의
number::Number
    =
    /\d+/
    ;