@@keyword :: fn

function_declaration::PinFunction
    =
    statement_declaration
    'fn' '(' [parameter:declaration_list] ')'
    '->' [type:type_specifier]
    '{' [code:code_block] '}'
    ;

function_parameter
    =
    declaration_list
    ;