const_initialization::Const
    =
        identifier:identifier
    ':' [type:type_specifier]
    ':' expression:expression
    ;

variable_declaration::Variable
    =
    identifier:identifier ':' type:type_specifier
    ;

variable_initialization::Variable
    =
    identifier:identifier ':' [type:type_specifier] '=' expression:expression
    ;