#include :: "term.ebnf"

# 표현식
expression
    =
    assert_not_statement @:expression_list
    ;

assert_not_statement
    =
    !statement_declaration
    ;

expression_list
    =
    | addition
    | subtraction
    | term
    ;

addition::Add
    =
    left:expression op:'+' ~ right:term
    ;

subtraction::Subtract
    =
    left:expression op:'-' ~ right:term
    ;

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | number
    | identifier
    ;