#include :: "term.ebnf"

# 표현식
expression_instruction
    =
    @:expression END
    ;

expression
    =
    | addition
    | subtraction
    | term
    ;

addition::Add
    =
    left:expression op:'+' ~ right:term
    ;

subtraction::Subtract
    =
    left:expression op:'-' ~ right:term
    ;
