# 항
term
    =
    | multiplication
    | division
    | factor
    ;

multiplication::Multiply
    =
    left:term op:'*' ~ right:factor
    ;

division::Divide
    =
    left:term op:'/' ~ right:factor
    ;

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | atom
    ;

atom
    =
    | number
    | identifier
    ;