
# 변수 / 상수 선언
statement
    =
    declaration_list
    ;

declaration_list
    =
    ",".{@:value_declaration_kinds}
    ;

value_declaration_kinds
    =
    | const_initialization
    | variable_initialization
    | variable_declaration
    ;

const_initialization::Const
    =
        identifier:identifier
    ':' [type:type_specifier]
    ':' expression:expression
    ;

variable_declaration::Variable
    =
    identifier:identifier ':' type:type_specifier
    ;

variable_initialization::Variable
    =
    identifier:identifier ':' [type:type_specifier] '=' expression:expression
    ;