@@grammar::PIN

start
    =
    | variable_declaration_list
    | {@:expression END}
    $
    ;

# 표현식
expression
    =
    | addition
    | subtraction
    | term
    ;

addition::Add
    =
    left:expression op:'+' ~ right:term
    ;

subtraction::Subtract
    =
    left:expression op:'-' ~ right:term
    ;

#include :: "pin/grammar/term.ebnf"
#include :: "pin/grammar/number.ebnf"
#include :: "pin/grammar/declaration.ebnf"

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | number
    | identifier
    ;


NL = /\n+/ ;
END = /\n/ ;