@@grammar::Pin

start
    =
    {@:code_block END}
    $
    ;

code_block
    =
    '\n'%{single_code}
    ;

single_code
    =
    | NL
    | @:statement
    | @:expression
    ;

code
    =
    | NL
    | {@:statement END}
    | {@:expression END}
    ;

# 표현식
expression
    =
    | addition
    | subtraction
    | term
    ;

addition::Add
    =
    left:expression op:'+' ~ right:term
    ;

subtraction::Subtract
    =
    left:expression op:'-' ~ right:term
    ;

#include :: "pin/grammar/term.ebnf"
#include :: "pin/grammar/declaration/declaration.ebnf"
#include :: "pin/grammar/token/token.ebnf"

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | number
    | identifier
    ;


NL = /\n+/ ;
END = /\n/ ;

