#include :: "value.ebnf"
#include :: "function.ebnf"

# 변수 / 상수 선언
statement
    =
    | function_declaration
    | declaration_list
    | statement_fail
    ;

statement_declaration = identifier:identifier '::' ;

statement_fail = -> &END;

declaration_list
    =
    ",".{@:value_declaration_kinds}
    ;

value_declaration_kinds
    =
    | const_initialization
    | variable_initialization
    | variable_declaration
    ;

