#include :: "value.ebnf"
#include :: "function.ebnf"

# 변수 / 상수 선언
statement_instruction
    =
    assert_is_statement @:statement END
    ;

assert_is_statement
    =
    &statement_declaration
    ;

statement
    =
    | function_declaration
    | declaration_list
    ;

statement_declaration = identifier:identifier '::' ;

declaration_list
    =
    ",".{@:value_declaration_type}
    ;

value_declaration_type
    =
    | const_initialization
    | variable_initialization
    | variable_declaration
    ;

