@@grammar::CALC

start
    =
    expression $
    ;

# 표현식
expression
    =
    | addition
    | subtraction
    | term
    ;

addition::Add
    =
    left:expression op:'+' ~ right:term
    ;

subtraction::Subtract
    =
    left:expression op:'-' ~ right:term
    ;

# 항
term
    =
    | multiplication
    | division
    | factor
    ;


multiplication::Multiply
    =
    left:term op:'*' ~ right:factor
    ;

division::Divide
    =
    left:term '/' ~ right:factor
    ;

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | number
    ;

number::Number
    =
    value:/\d+/
    ;

newlines = {'\n'};
terminate = '\n' | ';' ;