@@grammar::PIN

# include :: "pin/src/resources/type.ebnf"

# @@keyword:: when type

start
    =
    expression $
    ;

declaration =
    identifier
    ;

expression
    =
    | left:expression op:'+' ~ right:term
    | left:expression op:'-' ~ right:term
    | term
    ;

# 항
term
    =
    | left:term op:'*' ~ right:factor
    | left:term op:'/' ~ right:factor
    | factor
    ;

# 인수
factor
    =
    | '(' ~ @:expression ')'
    | number
    ;


identifier = /[a-zA-Zㄱ-ㅣ가-힣_][a-zA-Zㄱ-ㅣ가-힣0-9_]*/ ;
number = /\d+/ ;