type_specifier::PinType
    =
    | type_bool
    | type_int
    ;

type_int
    =
    | "i8" | "i16" | "i32" | "i64" | "isize" | "i128"
    | "u8" | "u16" | "u32" | "u64" | "usize" | "u128"
    ;

type_bool::bool = "bool" ;